#!/usr/bin/env bash
set -euo pipefail

# Generate config.php from environment variables if not present
if [ ! -f "/app/config.php" ]; then
  echo "[entrypoint] Creating /app/config.php from environment variables"

  : "${APP_BASE_URL:=http://localhost}"
  : "${APP_LANGUAGE:=english}"
  : "${APP_DEBUG:=false}"

  : "${DB_HOST:=mysql}"
  : "${DB_NAME:=easyappointments}"
  : "${DB_USER:=user}"
  : "${DB_PASS:=password}"

  cat > /app/config.php <<PHP
<?php
/* Auto-generated by container entrypoint */
class Config
{
    // GENERAL SETTINGS
    const BASE_URL   = '${APP_BASE_URL}';
    const LANGUAGE   = '${APP_LANGUAGE}';
    const DEBUG_MODE = ${APP_DEBUG};

    // DATABASE SETTINGS
    const DB_HOST     = '${DB_HOST}';
    const DB_NAME     = '${DB_NAME}';
    const DB_USERNAME = '${DB_USER}';
    const DB_PASSWORD = '${DB_PASS}';

    // GOOGLE CALENDAR SYNC (disabled by default)
    const GOOGLE_SYNC_FEATURE = false;
    const GOOGLE_CLIENT_ID = '';
    const GOOGLE_CLIENT_SECRET = '';
}
PHP
fi

# Ensure storage is writable
chmod -R 777 /app/storage || true

# Delegate to the base image entrypoint (starts php-fpm + nginx)
exec /opt/docker/bin/entrypoint.sh "$@"

